# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
    ]
