# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Description'),
        ),
    ]
