# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='bookapp.Books'),
        ),
    ]
